/**
 * Created by J...R on 18/10/2016.
 */
var fs = require('fs');
fs.mkdir('_Template', function () {

    fs.mkdir('./_Template/HTML', function () {
        fs.writeFile('./_Template/HTML/index.html', '<!DOCTYPE html>\n' +
            '<html>\n' +
            '<head>\n' +
            '<meta name="viewport" content="width=device-width"> <!-- For Mobile Use  --> \n' +
            '<meta name="description" content="My Website Description">\n' +
            '<link rel="stylesheet" type="text/css" href="../style/css/background.css">\n' +
            '<script src="../style/js/main.js"></script>\n' +
            '\t<title>Template.</title>\n' +
            '</head>\n' +
            '</body>\n' +
            'Hello World - html\n' +
            '<p id="example"></p>' +
            '</body>\n' +
            '</html>');
    });

    fs.mkdir('./_Template/style', function () {


        fs.mkdir('./_Template/style/css', function () {
            fs.writeFile('./_Template/style/css/background.css', 'body{\n' +
                '\tbackground-color: grey; //background colour example..\n' +
                '}')
        });
        fs.mkdir('./_Template/style/js', function () {
            fs.writeFile('./_Template/style/js/main.js', `document.write("<h1>Hello World! - JS</h1>");`);
            fs.writeFile('./_Template/style/js/Place Your javascript Here.txt', 'Please Your Javascript Here..\n\nGenerated By Jon');
        });
        fs.mkdir('./_Template/style/images', function () {
            fs.writeFile('./_Template/style/images/Place Your Images Here.txt', 'Place Your Images Here.\n\nGenerated By Jon');
        })


    });

    //TODO: NODE STUFF
    //
    fs.writeFile('./_Template/package.json', '{\n' +
        '\t"name": "my_package",\n' +
        '\t"version": "1.0.0",\n' +
        '\t"description": "Description About my Package..",\n' +
        '\t"main": "mod1.js",\n' +
        '\t"scripts": {\n' +
        '\t\t"test": "echo \\"Error: no test specified\\" && exit 1"\n' +
        '\t},' +
        '\t"author": "jon",\n' +
        '\t"license": "ISC",\n' +
        '\t"dependencies": {\n' +
        '\t\t"underscore": "^1.8.3",\n' +
        '\t\t"backbone": "^1.3.3",\n' +
        '\t\t"express": "~4.13.4"\n' +
        '\t},\n' +
        '\t"devDependencies": \n{' +
        '\t\t"grunt-contrib-cssmin": "^1.0.2",\n' +
        '\t\t"grunt-contrib-uglify": "^2.0.0"\n' +
        '\t}\n' +
        '}');


    fs.writeFile('./_Template/GET_NODE_MODULES.bat', 'echo off\n'
        + 'cls\n' +
        'echo Installing Node Modules from package.json...\n' +
        'npm update');


    fs.writeFile('./_Template/Readme.txt', "Must have Node Installed. \r\n" +
        "How To Use:\r\n" +
        "1. Run the GET_NODE_MODULES\r\n" +
        "this installed the modules..\r\n" +
        "\r\t Backbone | Express | underscore | Jquery | grunt(cssmin|uglify)\r\n" +
        "\r\n" +
        "\r\n" +
        "\r\n" +
        "USING GRUNT:\r\n" +
        "Once Packages are Installed to minimise the css type\r\n" +
        "grunt cssmin\r\n" +
        "\r\n" +
        "to minimise a javascript file..\r\n" +
        "grunt uglify\r\n" +
        "\r\n" +
        "*THESE FILES ARE SET TO A DEFAULT*\r\n" +
        "main.js and background.css\r\n" +
        "you can edit them in the gruntfile.js\r\n");

    //TODO: Creating Grunt File!

    fs.writeFile('./_Template/gruntfile.js', "module.exports = function(grunt) {\n" +
        "\tgrunt.initConfig({\n" +
        "\t\tpkg: grunt.file.readJSON('package.json'),\n" +
        "\n" +
        "\t\tuglify: {\n" +
        "\t\t\toptions:{\n" +
        "\t\t\t\tmanage: false\n" +
        "\t\t\t},\n" +
        "\t\t\tmy_target:{\n" +
        "\t\t\t\tfiles: {\n" +
        "\t\t\t\t\t'style/js/main.min.js' : ['style/js/main.js'] // making_newfile.min || [old_x.js]\n" +
        "\t\t\t\t}\n" +
        "\t\t\t}\n" +
        "\t\t},\n" +
        "\t\t\n" +
        "\t\tcssmin: {\n" +
        "\t\t\tdist: {\n" +
        "\t\t\t\t files: {\n" +
        "\t\t\t\t\t'style/css/background.min.css': ['style/css/background.css'] // new cssmin'd file | [old file] \n" +
        "\t\t\t\t}\n" +
        "\t\t\t}\n" +
        "\t\t}\n" +
        "\t});\n" +
        "\tgrunt.loadNpmTasks('grunt-contrib-uglify');\n" +
        "\tgrunt.loadNpmTasks('grunt-contrib-cssmin');\n" +
        "};");


});
