// Generated by CoffeeScript 1.11.0

/*
Notes:
	Splat is known as: ...
 */

(function() {
  var ListofPeople, combinedArray, csOutput, evensOnly, i, j, k, l, len, len1, len2, len3, name, oneTo10, oneTo20, peopleArray, randArray, sumOfArray, tenTo1, timesTable, user, userIndex, x;

  name = "Jon";

  csOutput = document.getElementById("csoutput");

  csOutput.innerHTML = "Welcome back " + name + " <br>";

  name = "Mark";

  switch (name) {
    case "Jon":
      csOutput.insertAdjacentHTML('beforeend', "You're my creator!<br>");
      break;
    case "Mark":
      csOutput.insertAdjacentHTML('beforeend', "You're not Jon<br>");
      break;
    case "Ken":
      csOutput.insertAdjacentHTML('beforeend', "Who are you?<br>");
      break;
    case "Joe":
      csOutput.insertAdjacentHTML('beforeend', "Uh oh!<br>");
      break;
    default:
      csOutput.insertAdjacentHTML('beforeend', "So like that is it.!<br>");
  }

  randArray = ["Immersive", false, 3.1562, 101101];

  csOutput.insertAdjacentHTML('beforeend', "Last 2: " + randArray.slice(2, 4) + " <br>");

  oneTo10 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  tenTo1 = [10, 9, 8, 7, 6, 5, 4, 3, 2, 1];

  timesTable = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  combinedArray = oneTo10.concat(tenTo1);

  oneTo10.push.apply(oneTo10, tenTo1);

  for (i = 0, len = oneTo10.length; i < len; i++) {
    x = oneTo10[i];
    csOutput.insertAdjacentHTML('beforeend', x + " <br>");
  }

  evensOnly = oneTo10.filter(function(x) {
    return x % 2 === 0;
  });

  csOutput.insertAdjacentHTML('beforeend', "Evens Only : " + (evensOnly.toString()) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "Max Number : " + (Math.max.apply(Math, oneTo10)) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "Min Number : " + (Math.min.apply(Math, oneTo10)) + "<br>");

  sumOfArray = oneTo10.reduce(function(x, y) {
    return x + y;
  });

  csOutput.insertAdjacentHTML('beforeend', "Sum of array: " + sumOfArray + " <br>");

  peopleArray = [
    {
      name: "Paul",
      age: 42
    }, {
      name: "Sue",
      age: 24
    }
  ];

  csOutput.insertAdjacentHTML('beforeend', "First Name: " + peopleArray[0].name + "<br>");


  /*
  Video: https://www.youtube.com/watch?v=Ku512-Z-Rx4
  Note: 7:19
  Note: Learning about objects which seems similar to JS/Ruby
  	+ Going to learn about loops 
  	+ and maybe more object practice.
   */

  csOutput.insertAdjacentHTML('beforeend', "Looping: <br><br>");

  oneTo20 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20];

  csOutput.insertAdjacentHTML('beforeend', "Evens: ");

  for (j = 0, len1 = oneTo20.length; j < len1; j++) {
    x = oneTo20[j];
    if (x % 2 === 0) {
      csOutput.insertAdjacentHTML('beforeend', x + " ");
    }
  }

  csOutput.insertAdjacentHTML('beforeend', "<br> Odds: ");

  for (k = 0, len2 = oneTo20.length; k < len2; k++) {
    x = oneTo20[k];
    if (x % 2 !== 0) {
      csOutput.insertAdjacentHTML('beforeend', "" + x);
    }
  }

  ListofPeople = ["Jon", "Kaylan", "Ken", "Alex", "Adam", "Chris", "Peter", "Isaac", "Smith", "Weir"];

  for (userIndex = l = 0, len3 = ListofPeople.length; l < len3; userIndex = ++l) {
    user = ListofPeople[userIndex];
    csOutput.insertAdjacentHTML('beforeend', "<br>Index: " + userIndex + " Name: " + user);
  }

}).call(this);
