// Generated by CoffeeScript 1.11.0
(function() {
  var Title, csOutput, factorial, getRandNum, helloFunc, personsAge, sumNums,
    slice = [].slice;

  Title = "Function Practice";

  csOutput = document.getElementById("csoutput");

  csOutput.innerHTML = "Welcome to:  " + Title + " <br>";


  /*
  Functions:
  	similar to ruby they need to be defined first. (top of file / include from seperate file)
   */

  helloFunc = function(name) {
    return "Hello " + name;
  };

  csOutput.insertAdjacentHTML('beforeend', (helloFunc("Jon")) + "<br>");

  getRandNum = function() {
    return Math.floor(Math.random() * 100) + 1;
  };

  csOutput.insertAdjacentHTML('beforeend', "Ranom Number: " + (getRandNum()) + "<br>");

  sumNums = function() {
    var i, len, sum, vars, x;
    vars = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    sum = 0;
    for (i = 0, len = vars.length; i < len; i++) {
      x = vars[i];
      sum += x;
    }
    return sum;
  };

  csOutput.insertAdjacentHTML('beforeend', "Sum: " + (sumNums(1, 9, 5, 2, 3, getRandNum())) + "<br>");

  personsAge = function(age) {
    if (age == null) {
      age = null;
    }
    if (age === null) {
      return "Age wasn't specified. default is null.";
    } else if (age <= 17) {
      return "You're unable to vote";
    } else {
      return "You're allowed to vote. Woo!";
    }
  };

  csOutput.insertAdjacentHTML('beforeend', "Jons Vote: " + (personsAge()) + "<br>");

  factorial = function(x) {
    if (x < 0) {
      return 0;
    }
    if (x === 0 || x === 1) {
      return 1;
    }
    return x * factorial(x - 1);
  };

  csOutput.insertAdjacentHTML('beforeend', "Factorial of 4: " + (factorial(5)));


  /*Whats Happening with factorial
  4 x 3 x 2 x 1 = 24
  is it loops through it takes a number away
  if it x = 1/0 return 1
  	if it = 0 return 0
   */

}).call(this);
