// Generated by CoffeeScript 1.11.0
(function() {
  var Title, csOutput, i, monkeys, said, x;

  Title = "Jon";

  csOutput = document.getElementById("csoutput");

  csOutput.innerHTML = "Welcome to:  " + Title + " <br>";

  i = 0;

  while ((i += 1) <= 10) {
    csOutput.insertAdjacentHTML('beforeend', "i = " + i + "<br>");
  }

  monkeys = 10;

  said = "no more monkeys jumping on the bed.";

  while (monkeys -= 1) {
    csOutput.insertAdjacentHTML('beforeend', monkeys + " Jumping on the bed. One fell of and bumped his head.<br>");
    if (monkeys === 1) {
      csOutput.insertAdjacentHTML('beforeend', "Mamma called the doctor and the doctor " + said + "<br>");
    }
  }

  x = 0;

  while (true) {
    csOutput.insertAdjacentHTML('beforeend', (++x) + "<br>");
    if (x === 5) {
      break;
    }
  }

}).call(this);
