// Generated by CoffeeScript 1.11.0
(function() {
  var Animal, Dog, Jon, csOutput, grover, sparky, x, y,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  csOutput = document.getElementById("csoutput");

  Jon = {
    name: "Jon",
    age: 27,
    street: "123 Longtis St"
  };

  csOutput.insertAdjacentHTML('beforeend', "Name : " + Jon.name + "<br>");

  Jon.food = "Cheesy Nachos";

  for (x in Jon) {
    y = Jon[x];
    csOutput.insertAdjacentHTML('beforeend', x + " is " + y + "<br>");
  }

  Animal = (function() {
    Animal.prototype.name = "No Name";

    Animal.prototype.height = 0;

    Animal.prototype.weight = 0;

    Animal.prototype.sound = "No Sound";

    Animal.numOfAnimals = 0;

    Animal.getNumOfAnimals = function() {
      return Animal.numOfAnimals;
    };

    function Animal(name, height1, weight1) {
      if (name == null) {
        name = "No Name";
      }
      this.height = height1 != null ? height1 : 0;
      this.weight = weight1 != null ? weight1 : 0;
      this.name = name;
      Animal.numOfAnimals++;
    }

    Animal.prototype.makeSound = function() {
      return "Says " + this.sound;
    };

    Animal.prototype.getInfo = function() {
      return this.name + " is " + this.height + "cm and weighs " + this.weight + "kg and " + (this.makeSound());
    };

    return Animal;

  })();

  grover = new Animal();

  grover.name = "Grover";

  grover.height = 60;

  grover.weight = 35;

  grover.sound = "woof";

  csOutput.insertAdjacentHTML('beforeend', (grover.getInfo()) + "<br>");

  Animal.prototype.isItBig = function() {
    if (this.height >= 45) {
      return "Yes";
    } else {
      return "No";
    }
  };

  csOutput.insertAdjacentHTML('beforeend', "Is Gover big? " + (grover.isItBig()) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "Number of Animals " + Animal.getNumOfAnimals + "<br>");

  Dog = (function(superClass) {
    extend(Dog, superClass);

    Dog.prototype.sound2 = "No Sound";

    function Dog(name, height, weight) {
      if (name == null) {
        name = "No Name";
      }
      if (height == null) {
        height = 0;
      }
      if (weight == null) {
        weight = 0;
      }
      Dog.__super__.constructor.call(this, name, height, weight);
    }

    Dog.prototype.makeSound = function() {
      return Dog.__super__.makeSound.apply(this, arguments) + (" and " + this.sound2);
    };

    return Dog;

  })(Animal);

  sparky = new Dog("Sparky", 30, 20);

  sparky.sound = "Wooooooof!";

  sparky.sound2 = "Growl!";

  csOutput.insertAdjacentHTML('beforeend', (sparky.getInfo()) + "<br>");

}).call(this);
