// Generated by CoffeeScript 1.11.0
(function() {
  $(document).ready(function() {
    var $x;
    $('#start_box').text('click here to move this text. it will be reversed..');
    $x = $('#start_box').html();
    $("#start_box").click(function() {
      var $backway;
      $backway = $x.split("").reverse().join("");
      $("#end_box").html("<b>Reversed</b>: <br>" + $backway);
      return $("#start_box").text("");
    });
    return $("#end_box").click(function() {
      $("#end_box").text("");
      return $("#start_box").text($x);
    });
  });

}).call(this);
